//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDeID { get; set; }
        public Nullable<int> OrderDeProID { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> OrderDeQuan { get; set; }
        public Nullable<decimal> OrderDePrice { get; set; }
        public Nullable<System.DateTime> OrderDeDate { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
