//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProID { get; set; }
        public string ProName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ProImage { get; set; }
        public Nullable<int> CagetoryID { get; set; }
        public Nullable<int> ProSupplier { get; set; }
        public Nullable<int> ProColor { get; set; }
        public Nullable<int> ProOrder { get; set; }
        public Nullable<int> ProStock { get; set; }
    
        public virtual Cagetories Cagetories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
